version: "3.8"

services:
  bot:
    build: .
    container_name: down_again_bot
    restart: "unless-stopped"
    environment:
      - BOT_TOKEN = ${BOT_TOKEN}
      - CHANNEL_ID = ${CHANNEL_ID}
      - TIMEZONE = ${TIMEZONE}
    networks:
      - db_network
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6-jammy
    container_name: down_again_mongodb
    restart: "unless-stopped"
    networks:
      - db_network
    volumes:
      - db_data:/data/db
    env_file:
      - .env
  
  mongo_express:
    image: mongo-express:1.0.0
    container_name: down_again_mongo_express
    restart: "unless-stopped"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME = ${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD = ${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_OPTIONS_READONLY: "true"
      - ME_CONFIG_DOCUMENTS_PER_PAGE: 100
    networks:
      - db_network
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo


volumes:
  db_data:

networks:
  db_network:
    driver: bridge
