version: "3.8"

services:
  bot:
    build: .
    container_name: fell_again_bot
    restart: "unless-stopped"
    environment:
      - BOT_TOKEN = ${BOT_TOKEN}
      - CHANNEL_ID = ${CHANNEL_ID}
    networks:
      - db_network
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: fell_again_mongodb
    image: mongo:6-jammy
    networks:
      - db_network
    volumes:
      - db_data:/data/db
    env_file:
      - .env


volumes:
  db_data:

networks:
  db_network:
    driver: bridge
